Pastagram/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),

]
if settings.DEBUG:
    urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(prefix=settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Pastagram/posts/urls.py
from django.urls import path
from .views import feeds, comment_add, comment_delete, post_add, tags, post_detail, post_like, img_select, test_add
from django.conf.urls.static import static
from django.conf import settings

app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name="feeds"),
    path("comment_add/", comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>", comment_delete, name="comment_delete"),
    path("post_add/", post_add, name="post_add"),
    path("tags/<str:tag_name>", tags, name="tags"),
    path("<int:post_id>/", post_detail, name="post_detail"),
    path("<int:post_id>/like/", post_like, name="post_like"),
    path("img_select/", img_select, name="img_select"),
    path("test_add/", test_add, name="test_add"),

]

Pastagram/posts/forms.py
from django import forms
from .models import Comment, Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "post",
            "content",
        ]
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "placeholder": "댓글 달기...",
                    "class": "comment-content-class",
                }
            )
        }

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["content"]
        widgets = {
            "content": forms.Textarea(attrs={"class": "post-content-class"})
        }

Pastagram/posts/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Post, Comment, PostImage, HashTag
from .forms import CommentForm, PostForm
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse

import requests
import urllib
from bs4 import BeautifulSoup as bs

def feeds(request):
    # 요청에 포함된 사용자가 로그인하지 않은 경우
    if not request.user.is_authenticated:
        return redirect("/users/login/")

    # 모든 글 목록을 템플릿으로 전달
    posts = Post.objects.all()
    comment_form = CommentForm()
    context = {
        "posts": posts,
        "comment_form": comment_form,
               }
    return render(request, "posts/feeds.html", context)

@require_POST   # 댓글 작성을 처리할 View, Post 요청만 허용한다.
def comment_add(request):
    # request.POST로 전달된 데이터를 사용해 CommentForm 인스턴스를 생성
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # commit=False 옵션으로 메모리상에 Comment 객체 생성
        comment = form.save(commit=False)

        # Comment 생성에 필요한 사용자 정보를 request에서 가져와 할당
        comment.user = request.user

        # DB에 Comment 객체 저장
        comment.save()

        # URL로 'next' 값을 전달받았다면, 댓글 작성 완료 후 전달받은 값으로 이동한다
        url_next = request.GET.get("next") or reverse("posts:feeds") + f"#post-{comment.post.id}"
        return HttpResponseRedirect(url_next)

@require_POST
def comment_delete(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if comment.user == request.user:
        comment.delete()
        return HttpResponseRedirect(f"/posts/feeds/#post-{comment.post.id}")
    else:
        return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다")

selected_image_urls = []
keyword = ''
def post_add(request):
    global selected_image_urls
    global keyword

    if 'img_select' in request.META.get('HTTP_REFERER', ''):
        selected_image_urls = request.POST.getlist('selectedImages')
        keyword = request.POST.get('keyword')

    elif 'feeds' in request.META.get('HTTP_REFERER', ''):
        selected_image_urls = []

    if request.method == "POST":
        # request.POST로 온 데이터 ("content")는 PostForm으로 처리
        form = PostForm(request.POST, request.FILES)
        submit = request.POST.get('submit_check', '')

        if submit == "submit" and form.is_valid():

            # Post의 "user" 값은 request에서 가져와 자동 할당한다.
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            print("aaa:", request.FILES.getlist("images"))
            # Post를 생성한 후
            # request.FILES.getlist("images")로 전송된 이미지들을 순회하며 PostImage 객체를 생성한다.
            for image_file in request.FILES.getlist("images"):
                # request.FILES 또는 request.FILES.getlist()로 가져온 파일은
                # Model의 imageField 부분에 곧바로 할당한다.

                PostImage.objects.create(
                    post=post,
                    photo=image_file,
                )

            for selected_image_url in selected_image_urls:
                my_model_instance = PostImage.objects.create(
                    post=post,
                    image_url=selected_image_url,
                )
                my_model_instance.save_image_from_url(keyword, request.user)

            tag_string = request.POST.get("tags")  # input의 name값을 적으면 input값을 들고 온다.
            if tag_string:
                tag_names = [tag_name.strip() for tag_name in tag_string.split(",")]
                for tag_name in tag_names:
                    tag, _ = HashTag.objects.get_or_create(name=tag_name)
                    # get_or_create로 생성하거나 가져온 HashTag 객체를 Post의 tags에 추가한다
                    post.tags.add(tag)

            url = reverse("posts:feeds") + f"#post-{post.id}"
            return HttpResponseRedirect(url)

    # GET 요청일 때는 빈 form을 보여주도록 한다.
    else:
        form = PostForm()

    context = {"form": form,
               "selected_image_urls": selected_image_urls,

               }
    return render(request, "posts/post_add.html", context)

def tags(request, tag_name):
    try:
        # HTML에서 요청한 해시태그(tag_name)에 해당하는 HashTag모델(DB)의 객체를 불러옴
        tag = HashTag.objects.get(name=tag_name)
    except HashTag.DoesNotExist:
        # tag_name에 해당하는 HashTag를 찾지 못한 경우, 빈 쿼리셋을 돌려준다.
        posts = Post.objects.none()
    else:   # 찾은경우 태그된 Post의 쿼리셋을 불러온다.
        posts = Post.objects.filter(tags=tag)

    context = {
        "tag_name": tag_name,
        "posts": posts,
    }
    return render(request, 'posts/tags.html', context)

def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comment_form = CommentForm()
    context = {
        "post": post,
        "comment_form": comment_form,
    }
    return render(request, "posts/post_detail.html", context)

def post_like(request, post_id):
    post = Post.objects.get(id=post_id)
    user = request.user

    # 사용자가 "좋아료를 누른 Post 목록"에 "좋아요 버튼을 누른 Post"가 존재한다면
    if user.like_posts.filter(id=post.id).exists():
        # 좋아요 목록에서 삭제한다
        user.like_posts.remove(post)
    # 존재하지 않는다면 좋아요 목록에 추가한다
    else:
        user.like_posts.add(post)



    # next로 값이 전달되었다면 해당 위치로, 전달되지 않았다면 피드 페이지에서 해당 Post 위치로 이동한다.
    url_next = request.GET.get("next") or reverse("posts:feeds") + f"#post-{post.id}"
    return HttpResponseRedirect(url_next)




def img_select(request):
    img_url_list = []

    if request.method == "POST":
        if request.POST['keyword'] != "":
            keyword = request.POST['keyword']
            cnt = int(request.POST['cnt'])

            print(keyword)
            print(cnt)

            keyword_quote = urllib.parse.quote(keyword)
            url = 'https://images.search.yahoo.com/search/images;_ylt=Awr9IlCx7FdgSIEAGZJXNyoA;_ylu==Y29sbwNncTEEcG9zAzEEdnRpZANDMDE2MF8xBHNlYwNwaXZz?p='
            url = url + keyword_quote + '&fr2=piv-web&fr=yfp-t'
            response = requests.get(url)
            soup = bs(response.text, 'html.parser')
            tag_imgs = soup.select('li.ld a > img')

            for tag_img in tag_imgs:
                img_url_list.append(tag_img.attrs['data-src'])

            context = {
                "img_url_list": img_url_list[:cnt],
                "keyword": keyword,
            }
        else:
            context = {}
            print('aa')
    else:
        context = {}
        print('bb')

    print('cc')

    return render(request, 'posts/img_select.html', context)


def test_add(request):
    pass
    # if request.method == 'POST':
    #     selected_image_urls = request.POST.getlist('selectedImages')
    #     print(selected_image_urls)
    #
    # return render(request, 'posts/img_select.html')
        # 여기에서 선택된 이미지의 URL을 처리하거나 다른 로직을 수행할 수 있습니다.
        # json으로 처리
        # return JsonResponse({'message': 'Success', 'selected_image_urls': selected_image_urls})

Pastagram/templates/posts/feeds.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
{% extends 'base_slider.html' %}
{% load custom_tags %}

</head>
<body>
{% block content %}

  <div id="feeds" class="post-container">
      {%for post in posts %}
            {% url 'posts:feeds' as action_redirect_to %}
            {% include 'posts/post.html' with action_redirect_url=action_redirect_to|concat:'#post-'|concat:post.id %}
      {% endfor %}
  </div>
{% endblock %}


</body>
</html>

Pastagram/templates/posts/img_select.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% extends 'base_nav.html' %}

     {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>


{% block content %}


<main class="select-main">

<div class="search-form">
    <form method="POST">
    {% csrf_token %}
        <input id="search-input" name="keyword" type="text" placeholder="검색할 이미지 명" required>

   <label for="select-count" id="select-label">이미지 개수</label>
        <select name="cnt" id="select-count">
            <option value="10"> 10
            <option value="20" selected> 20
            <option value="30"> 30
            <option value="40"> 40
            <option value="50"> 50
            <option value="60"> 60
    </select>
    <button type="submit" class="pasing_url_btn">검색</button>
    </form>
</div>






<div>
<form id="imageForm" method="post" action="{% url 'posts:post_add' %}">
        {% csrf_token %}
        <button align="right" type="submit" class="url_send" onclick="submitImages()">선택된 이미지 전송</button>

<div id="img_frame">
    {% for img_url in img_url_list %}

        <label class="image-checkbox-label">
            <img src="{{ img_url }}" alt="x" width="200px" height="200px" id="img_view">
            <input type="checkbox" class="input-checkbox" name="selectedImages" value="{{ img_url }}">
<!--            <span class="check-icon" style="background: url('') no-repeat;"></span>-->
            <img src="{% static 'image/check.png' %}" class="check-icon">
        </label>

    {% endfor %}
</div>
    <input type="hidden" name="keyword" value="{{ keyword }}">
    </form>
    </div>
</main>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

{% endblock %}
</body>
</html>

Pastagram/templates/posts/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>feeds</title>
{% load static %}

</head>
<body>


  <article id="post-{{ post.id }}" class="post">
      <header class="post-header">
          <a href="{% url 'users:profile' user_id=post.user.id %}">
          {% if post.user.profile_image %}
            <img src="{{ post.user.profile_image.url }}">
          {% endif %}
            <span>{{ post.user.username }}</span>
          </a>

          {% if user != post.user %}
            <form action="{% url 'users:follow' user_id=post.user.id %}?next={{ action_redirect_url }}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">
                    {% if post.user in user.following.all %}
                        Unfollow
                    {% else %}
                        Follow
                    {% endif %}
                </button>
            </form>
        {% endif %}
      </header>

      <div class="post-images splide">
          <div class="splide__track">
              <ul class="splide__list">
                  {% for image in post.postimage_set.all %}
                    {% if image.photo %}
                    <li class="splide__slide">
                        <img src="{{ image.photo.url }}" width="530" height="580">
                    </li>
                    {% endif %}
                  {% endfor %}
              </ul>
          </div>
      </div>

        <div class="post-content">
            {{ post.content|linebreaksbr }}
              <div class="post-tags">
                {% for tag in post.tags.all %}
                    <a href="{% url 'posts:tags' tag_name=tag.name %}">#{{ tag.name }}</a>
                {% endfor %}
              </div>
        </div>

        <div class="post-buttons">
          <form action="{% url 'posts:post_like' post_id=post.id %}"?next="{{ action_redirect_url }}" method="POST">
              {% csrf_token %}
                <button type="submit">
                {% if user in post.like_users.all %}
                        <img src="{% static 'image/like_active.png' %}" class="like-image-class">
                {% else %}
                        <img src="{% static 'image/like_inactive.png' %}" class="like-image-class">
                {% endif %}
                    {{ post.like_users.count }}
                </button>
          </form>
          <span>댓글 {{ post.comment_set.count }}</span>
        </div>

        <div class="post-comments">
            <ul>
            {% for comment in post.comment_set.all %}
                <li>
                    <span>{{ comment.user.username }}</span>
                    <span>{{ comment.content }}</span>
                    {% if user == comment.user %}
                        <form method="POST" action="{% url 'posts:comment_delete' comment_id=comment.id %}">
                            {% csrf_token %}
                            <button type="submit">삭제</button>
                        </form>
                    {% endif %}
                </li>
            {% endfor %}
            </ul>
        </div>

        <small>{{ post.created }}</small>
        <div class="post-comment-create">
            <form method="POST" action="{% url 'posts:comment_add' %}?next={{ action_redirect_url }}">
                {% csrf_token %}
                <input type="hidden" name="post" value="{{ post.id }}">
                {{ comment_form.content }} <!-- "class": "comment-content-class"-->
                    <button class="content-button-class" type="submit">게시</button>
            </form>
        </div>
  </article>

  <script type="text/javascript" src="{% static 'js/style.js' %}"></script>

</body>
</html>

Pastagram/templates/posts/post_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base_nav.html' %}

{% block content %}
<div id="post-add">
  <h2 id="post-add-h2">게시물 작성</h2>
    <form method="POST" enctype="multipart/form-data" action="{% url 'posts:post_add' %}">
        {% csrf_token %}
        <div id="img-viewer">

            <input id="img_file_select" name="images" type="file" multiple  onchange="displayFileName(this)">
            <label for="img_file_select" class="file_custom_label">
                <span class="file_btn">파일선택</span>
                 <span class="file_name">파일을 선택해주세요.</span>
            </label>



            <div id="img_select_div">
           <a href="{% url 'posts:img_select' %}">
            <button class="custom-img-btn" type="button">
                <span id="btn-span">포털사이트에서 이미지 가져오기</span>
            </button>
            </a>
            </div>

            <div class="print-div">
            {% for selected_image_url in selected_image_urls %}
            <img src="{{ selected_image_url }}" alt="" class="print-image">
            {% endfor %}
            </div>

        </div>

            <label>내용</label>
        {{ form.content }}
        <div>
            <label for="id_tags">해시태그</label>
            <input id="id_tags" name="tags"
                    type="text" placeholder="쉼표(,)로 구분하여 여러 태그 입력">
        </div>
        <input type="hidden" name="submit_check" id="submit_check-id" value="">
        <button type="submit" id="myButton" onclick="postSubmit()">게시</button>

    </form>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>
function postSubmit() {
    $("#submit_check-id").val("submit");
    $("#myButton").submit();
}



</script>

{% endblock %}
</body>
</html>


Pastagram/templates/posts/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base_slider.html' %}
{% block content %}
<div id="feeds" class="post-container">
    {% url 'posts:post_detail' post.id as action_redirect_to %}
    {% include 'posts/post.html' with action_redirect_url=action_redirect_to %}
</div>
{% endblock %}
</body>
</html>

Pastagram/templates/posts/tags.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base_nav.html' %}
{% block content %}

<div id="tags">
  <header class="tags-header">
    <h2>#{{ tag_name }}</h2>
    <div>게시물 {{ posts.count }}</div>
  </header>
  <div class="post-grid-container">
    {% for post in posts %}
      {% if post.postimage_set.first and post.postimage_set.first.photo %}
      <div class="post-grid">
        <a href="{% url 'posts:post_detail' post_id=post.id %}">
          <img src="{{ post.postimage_set.first.photo.url }}" alt="">
        </a>
      </div>
      {% endif %}
      {% empty %}
        <p>검색된 게시물이 없습니다</p>
    {% endfor %}
  </div>
</div>
{% endblock %}
</body>
</html>
