pastagram/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(prefix=settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pastagram/posts/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .views import feeds, comment_add, comment_delete, post_add, \
tags, post_detail, post_like, search_img, select_img


app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name="feeds"),
    path("comment_add/", comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>", comment_delete, name="comment_delete"),
    path("post_add/", post_add, name="post_add"),
    path("tags/<str:tag_name>", tags, name="tags"),
    path("<int:post_id>/", post_detail, name="post_detail"),
    path("<int:post_id>/like/", post_like, name="post_like"),
    path("search_img/", search_img, name="search_img"),
    path("select_img/", select_img, name="select_img"),

]

pastagram/users/urls.py
from django.urls import path
from .views import login_view, logout_view, signup, profile, followers, following, follow

app_name = "users"
urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup, name="signup"),
    path("<int:user_id>/profile/", profile, name="profile"),
    path("<int:user_id>/followers/", followers, name="followers"),
    path("<int:user_id>/following/", following, name="following"),
    path("<int:user_id>/follow/", follow, name="follow"),

]

pastagram/posts/models.py
from django.db import models
from django.core.files import File
from tempfile import NamedTemporaryFile
import requests

class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    content = models.TextField("내용", blank=True, null=True)
    created = models.DateTimeField("생성일시", auto_now_add=True)
    tags = models.ManyToManyField("posts.HashTag", verbose_name="해시태그 목록", blank=True)

    def __str__(self):
        return f"{self.user.username}의 Post(id: {self.id})"

class PostImage(models.Model):

    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE,
    )
    photo = models.ImageField("사진", upload_to="post")
    image_url = models.URLField(blank=True, null=True)


    def save_image_from_url(self, keyword, user):
        response = requests.get(self.image_url)
        if response.status_code == 200:
            img_temp = NamedTemporaryFile(delete=True)
            img_temp.write(response.content)
            img_temp.flush()
            self.photo.save(f"{user}_{keyword}_image.jpg", File(img_temp), save=True)


class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,   # 한 줄 건너뛰어서 괄호를 닫았으니 ,을 찍어야 한다.
    )
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE) # 바로 닫았으니 , 필요없음
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)

class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

pastagram/posts/forms.py
from django import forms
from .models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "post",
            "content",
        ]
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "placeholder": "댓글 달기...",
                    "class": "comment-content-class",
                }
            )
        }

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["content"]
        widgets = {
            "content": forms.Textarea(attrs={"class": "post-content-class"})
        }

pastagram/posts/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Post, Comment, PostImage, HashTag
from .forms import CommentForm, PostForm
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse
from .image_parser import parse_images

def feeds(request):
    if not request.user.is_authenticated:
        return redirect("/users/login/")

    posts = Post.objects.all()
    comment_form = CommentForm()

    request.session.pop('selected_img_urls', None)
    context = {
        "posts": posts,
        "comment_form": comment_form,
        }
    
    return render(request, "posts/feeds.html", context)

@require_POST
def comment_add(request):
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.save()

        url_next = request.GET.get("next") or reverse("posts:feeds") + f"#post-{comment.post.id}"

        return HttpResponseRedirect(url_next)

@require_POST
def comment_delete(request, comment_id):
    comment = Comment.objects.get(id=comment_id)

    if comment.user == request.user:
        comment.delete()
        return HttpResponseRedirect(f"/posts/feeds/#post-{comment.post.id}")

    else:
        return HttpResponseForbidden("해당 댓글을 삭제할 권한이 없습니다")

def search_img(request):
    if request.method == "POST":
        keyword = request.POST['keyword'].strip()

        if len(keyword) > 0:
            cnt = int(request.POST['cnt'])
            request.session['img_url_list'] = parse_images(keyword, cnt)
            request.session['keyword'] = keyword
            return redirect('posts:select_img')

        else:
            context = {'error_message': "키워드를 다시 입력해주세요."}

    return render(request, 'posts/search_img.html')


def select_img(request):
    if request.method == "POST":
        request.session['selected_img_urls'] = request.POST.getlist('selectedImages', '')
        return redirect('posts:post_add')
    
    img_url_list = request.session.pop('img_url_list', '')
    keyword = request.session.pop('keyword', '')

    context = {
        "img_url_list": img_url_list,
        "keyword": keyword,
    }
    return render(request, 'posts/select_img.html', context)



def post_add(request):
    
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        local_image = request.FILES.getlist("images")
        selected_img_urls = request.session.pop('selected_img_urls', '')
        keyword = request.session.pop('keyword', '')
        print('진입 : ', selected_img_urls)

        if selected_img_urls or local_image:
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            for image_file in local_image:
                PostImage.objects.create(
                    post=post,
                    photo=image_file,
                )

            for selected_image_url in selected_img_urls:
                PostImage_instance = PostImage.objects.create(
                    post=post,
                    image_url=selected_image_url,
                ) 
                PostImage_instance.save_image_from_url(keyword, request.user)

            tag_string = request.POST.get("tags")  # input의 name값을 적으면 input값을 들고 온다.
            if tag_string:
                tag_names = [tag_name.strip() for tag_name in tag_string.split(",")]
                for tag_name in tag_names:
                    tag, _ = HashTag.objects.get_or_create(name=tag_name)
                    post.tags.add(tag)

            url = reverse("posts:feeds") + f"#post-{post.id}"
            return HttpResponseRedirect(url)

        else:
            context = {'error_message': "한 개 이상의 이미지가 필요합니다."}
            return render(request, "posts/post_add.html", context)

    form = PostForm()
    selected_img_urls = request.session.get('selected_img_urls', '')

    context = {
        "selected_img_urls": selected_img_urls,
        "form": form,
        }  
    return render(request, "posts/post_add.html", context)

def tags(request, tag_name):
    try:
        # HTML에서 요청한 해시태그(tag_name)에 해당하는 HashTag모델(DB)의 객체를 불러옴
        tag = HashTag.objects.get(name=tag_name)
    except HashTag.DoesNotExist:
        # tag_name에 해당하는 HashTag를 찾지 못한 경우, 빈 쿼리셋을 돌려준다.
        posts = Post.objects.none()
    else:   # 찾은경우 태그된 Post의 쿼리셋을 불러온다.
        posts = Post.objects.filter(tags=tag)

    context = {
        "tag_name": tag_name,
        "posts": posts,
    }
    return render(request, 'posts/tags.html', context)

def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comment_form = CommentForm()
    context = {
        "post": post,
        "comment_form": comment_form,
    }
    return render(request, "posts/post_detail.html", context)

def post_like(request, post_id):
    post = Post.objects.get(id=post_id)
    user = request.user

    # 사용자가 "좋아료를 누른 Post 목록"에 "좋아요 버튼을 누른 Post"가 존재한다면
    if user.like_posts.filter(id=post.id).exists():
        # 좋아요 목록에서 삭제한다
        user.like_posts.remove(post)
    # 존재하지 않는다면 좋아요 목록에 추가한다
    else:
        user.like_posts.add(post)

    # next로 값이 전달되었다면 해당 위치로, 전달되지 않았다면 피드 페이지에서 해당 Post 위치로 이동한다.
    url_next = request.GET.get("next") or reverse("posts:feeds") + f"#post-{post.id}"
    return HttpResponseRedirect(url_next)




pastagram/templates/posts/feeds.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
{% extends 'base-posts.html' %}
{% load custom_tags %}

</head>
<body>
{% block content %}

  <div id="feeds" class="post-container">
      {%for post in posts %}
            {% url 'posts:feeds' as action_redirect_to %}
            {% include 'posts/post.html' with action_redirect_url=action_redirect_to|concat:'#post-'|concat:post.id %}
      {% endfor %}
  </div>
{% endblock %}


</body>
</html>

pastagram/templates/posts/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>feeds</title>
{% load static %}

</head>
<body>


  <article id="post-{{ post.id }}" class="post">
      <header class="post-header">
          <a href="{% url 'users:profile' user_id=post.user.id %}">
          {% if post.user.profile_image %}
            <img src="{{ post.user.profile_image.url }}">
          {% endif %}
            <span>{{ post.user.username }}</span>
          </a>

          {% if user != post.user %}
            <form action="{% url 'users:follow' user_id=post.user.id %}?next={{ action_redirect_url }}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">
                    {% if post.user in user.following.all %}
                        <span>Unfollow</span>
                    {% else %}
                        <span>Follow</span>
                    {% endif %}
                </button>
            </form>
        {% endif %}
      </header>

      <div class="post-images splide">
          <div class="splide__track">
              <ul class="splide__list">
                  {% for image in post.postimage_set.all %}
                    {% if image.photo %}
                    <li class="splide__slide">
                        <img src="{{ image.photo.url }}" width="530" height="580">
                    </li>
                    {% endif %}
                  {% endfor %}
              </ul>
          </div>
      </div>

        <div class="post-content">
            {{ post.content|linebreaksbr }}
              <div class="post-tags">
                {% for tag in post.tags.all %}
                    <a href="{% url 'posts:tags' tag_name=tag.name %}">#{{ tag.name }}</a>
                {% endfor %}
              </div>
        </div>

        <div class="post-buttons">
          <form action="{% url 'posts:post_like' post_id=post.id %}"?next="{{ action_redirect_url }}" method="POST">
              {% csrf_token %}
                <button type="submit">
                {% if user in post.like_users.all %}
                        <img src="{% static 'image/like_active.png' %}" class="like-image-class">
                {% else %}
                        <img src="{% static 'image/like_inactive.png' %}" class="like-image-class">
                {% endif %}
                    {{ post.like_users.count }}
                </button>
          </form>
          <span>댓글 {{ post.comment_set.count }}</span>
        </div>

        <div class="post-comments">
            <ul>
            {% for comment in post.comment_set.all %}
                <li>
                    <span>{{ comment.user.username }}</span>
                    <span>{{ comment.content }}</span>
                    {% if user == comment.user %}
                        <form method="POST" action="{% url 'posts:comment_delete' comment_id=comment.id %}">
                            {% csrf_token %}
                            <button type="submit">삭제</button>
                        </form>
                    {% endif %}
                </li>
            {% endfor %}
            </ul>
        </div>

        <small>{{ post.created }}</small>
        <div class="post-comment-create">
            <form method="POST" action="{% url 'posts:comment_add' %}?next={{ action_redirect_url }}">
                {% csrf_token %}
                <input type="hidden" name="post" value="{{ post.id }}">
                {{ comment_form.content }} <!-- "class": "comment-content-class"-->
                    <button class="content-button-class" type="submit">게시</button>
            </form>
        </div>
  </article>

  <script type="text/javascript" src="{% static 'js/style.js' %}"></script>

</body>
</html>

pastagram/templates/posts/post_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <title>Title</title>
</head>
<body>
{% extends 'base-posts.html' %}

{% block content %}
<div id="post-add">
  <h2 id="post-add-h2">게시물 작성</h2>
    <form method="POST" enctype="multipart/form-data" action="{% url 'posts:post_add' %}">
        {% csrf_token %}
        <div class="img-viewer">
            <div class="button-grid">
                <!-- <div class="search_img_div"> -->
            <a href="{% url 'posts:search_img' %}" id="searchButton" class="image-select-button">
                <span class="file-select-span">포털사이트 이미지 가져오기</span>
            </a>
       
                <!-- </div> -->
                
       
                <!-- <div class="file-select-div"> -->
            <label for="img_file_select" id="fileButton" class="image-select-button">
                <input id="img_file_select" name="images" type="file" multiple  onchange="displayFileName(this)">
                <span class="file-select-span">로컬 파일 선택</span>
            </label>
                        
                <!-- </div> -->
            </div>
            <span class="file_name"></span>
            {% if error_message %}
            <p id="none-image-error">{{ error_message }}</p>
            {% endif %}


            

            <div class="print-div">
            {% for selected_image_url in selected_img_urls %}
            <img src="{{ selected_image_url }}" alt="" class="print-image">
            {% endfor %}
            </div>

        </div>

        <label>내용</label>
        {{ form.content }}
        
        <div>
            <label for="id_tags">해시태그</label>
            <input id="id_tags" name="tags"
                    type="text" placeholder="쉼표(,)로 구분하여 여러 태그 입력">
        </div>
        <!-- <input type="hidden" name="submit_check" id="submit_check-id" value=""> -->
        <button type="submit" id="myButton">게시</button>

    </form>
</div>

<!-- <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script> -->

<!-- <script>
function postSubmit() {
    $("#submit_check-id").val("submit");
    $("#myButton").submit();
}



</script> -->

{% endblock %}
</body>
</html>


pastagram/templates/posts/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base-posts.html' %}
{% block content %}
<div id="feeds" class="post-container">
    {% url 'posts:post_detail' post.id as action_redirect_to %}
    {% include 'posts/post.html' with action_redirect_url=action_redirect_to %}
</div>
{% endblock %}
</body>
</html>

pastagram/templates/posts/search_img.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% extends 'base-posts.html' %}
    <!-- <script>
        // HTML 템플릿 태그를 사용하여 CSRF 토큰을 JavaScript 변수에 할당
        var csrf_token = '{{ csrf_token }}';
        var postAddUrl = '{% url 'posts:post_add' %}';
    </script> -->

     {% load static %}

    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->

</head>
<body>


{% block content %}


<main class="select-main">

<div class="search-form">
    <form method="POST">
    {% csrf_token %}
        <input id="search-input" name="keyword" type="text" placeholder="검색할 이미지 명" required>
        
        <label for="select-count" id="select-label">이미지 개수</label>
        <select name="cnt" id="select-count">
            <option value="10"> 10
            <option value="20" selected> 20
            <option value="30"> 30
            <option value="40"> 40
            <option value="50"> 50
            <option value="60"> 60
    </select>
    <button type="submit" class="pasing_url_btn">검색</button>
    {% if error_message %}
    <p id="keyword-error">{{ error_message }}</p>
    {% endif %}

    </form>

</div>






</main>


<!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> -->

{% endblock %}
</body>
</html>

pastagram/templates/posts/select_img.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
{% extends 'base-posts.html' %}

    {% load static %}


</head>
<body>
    {% block content %}
    <div>
<!-- <form id="imageForm" method="post" action="{% url 'posts:post_add' %}"> -->
    <form id="imageForm" method="post">

        {% csrf_token %}
        <button type="submit" class="url_send">선택된 이미지 전송</button>
         
<div id="img_frame">
    {% for img_url in img_url_list %}

        <label class="image-checkbox-label">
            <img src="{{ img_url }}" alt="x" width="200px" height="200px" id="img_view">
            <input type="checkbox" class="input-checkbox" name="selectedImages" value="{{ img_url }}">
            <img src="{% static 'image/check.png' %}" class="check-icon">
        </label>

    {% endfor %}
</div>
    <input type="hidden" name="keyword" value="{{ keyword }}">
    </form>
    </div>

<!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> -->
{% endblock %}

</body>
</html>

pastagram/templates/posts/tags.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base-posts.html' %}
{% block content %}

<div id="tags">
  <header class="tags-header">
    <h2>#{{ tag_name }}</h2>
    <div>게시물 {{ posts.count }}</div>
  </header>
  <div class="post-grid-container">
    {% for post in posts %}
      {% if post.postimage_set.first and post.postimage_set.first.photo %}
      <div class="post-grid">
        <a href="{% url 'posts:post_detail' post_id=post.id %}">
          <img src="{{ post.postimage_set.first.photo.url }}" alt="">
        </a>
      </div>
      {% endif %}
      {% empty %}
        <p>검색된 게시물이 없습니다</p>
    {% endfor %}
  </div>
</div>
{% endblock %}
</body>
</html>
