pastagram/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(prefix=settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pastagram/posts/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .views import feeds, comment_add, comment_delete, post_add, \
tags, post_detail, post_like, search_img, select_img


app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name="feeds"),
    path("comment_add/", comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>", comment_delete, name="comment_delete"),
    path("post_add/", post_add, name="post_add"),
    path("tags/<str:tag_name>", tags, name="tags"),
    path("<int:post_id>/", post_detail, name="post_detail"),
    path("<int:post_id>/like/", post_like, name="post_like"),
    path("search_img/", search_img, name="search_img"),
    path("select_img/", select_img, name="select_img"),

]

pastagram/users/urls.py
from django.urls import path
from .views import login_view, logout_view, signup, profile, followers, following, follow

app_name = "users"
urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup, name="signup"),
    path("<int:user_id>/profile/", profile, name="profile"),
    path("<int:user_id>/followers/", followers, name="followers"),
    path("<int:user_id>/following/", following, name="following"),
    path("<int:user_id>/follow/", follow, name="follow"),

]

pastagram/posts/models.py
from django.db import models
from django.core.files import File
from tempfile import NamedTemporaryFile
import requests

class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    content = models.TextField("내용", blank=True, null=True)
    created = models.DateTimeField("생성일시", auto_now_add=True)
    tags = models.ManyToManyField("posts.HashTag", verbose_name="해시태그 목록", blank=True)

    def __str__(self):
        return f"{self.user.username}의 Post(id: {self.id})"

class PostImage(models.Model):

    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE,
    )
    photo = models.ImageField("사진", upload_to="post")
    image_url = models.URLField(blank=True, null=True)


    def save_image_from_url(self, keyword, user):
        response = requests.get(self.image_url)
        if response.status_code == 200:
            img_temp = NamedTemporaryFile(delete=True)
            img_temp.write(response.content)
            img_temp.flush()
            self.photo.save(f"{user}_{keyword}_image.jpg", File(img_temp), save=True)


class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,   # 한 줄 건너뛰어서 괄호를 닫았으니 ,을 찍어야 한다.
    )
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE) # 바로 닫았으니 , 필요없음
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)

class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

pastagram/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import os
from django.conf import settings


class User(AbstractUser):
    
    profile_image = models.ImageField(
        "프로필 이미지", 
        upload_to='users/profile/', 
        default='profile_default.png', 
        blank=True,
    )
    like_posts = models.ManyToManyField(
        "posts.Post",
        verbose_name="좋아요 누른 Post 목록",
        related_name="like_users",
        blank=True,
    )
    following = models.ManyToManyField(
        "self",
        verbose_name="팔로우 중인 사용자들",
        related_name="followers",
        symmetrical=False,
        through="users.Relationship",
    )

    def __str__(self):
        return self.username


class Relationship(models.Model):
    from_user = models.ForeignKey(
        "users.User",
        verbose_name="팔로우를 요청한 사용자",
        related_name="following_relationships",
        on_delete=models.CASCADE,
    )
    to_user = models.ForeignKey(
        "users.User",
        verbose_name="팔로우 요청의 대상",
        related_name="follower_relationships",
        on_delete=models.CASCADE,
    )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"팔로잉 ({self.from_user} -> {self.to_user})"

pastagram/users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import User
from pathlib import Path
from PIL import Image
from django.core.files.base import ContentFile
from django.conf import settings
import os


class LoginForm(forms.Form):
    username = forms.CharField(
        min_length=3,
        widget=forms.TextInput(
            attrs={"placeholder": "사용자명 (3자리 이상)"},
        ),
    )
    password = forms.CharField(
        min_length=4,
        widget=forms.PasswordInput(
            attrs={"placeholder": "비밀번호 (4자리 이상)"},
        ),
    )


class SignupForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    profile_image = forms.ImageField(required=False)


    def clean_username(self):
        username = self.cleaned_data["username"]

        if User.objects.filter(username=username).exists():
            raise ValidationError(f"입력한 사용자면({username})은 이미 사용 중입니다")
        return username

    def clean(self):
        password = self.cleaned_data["password"]
        password2 = self.cleaned_data["password2"]

        if password != password2:
            # password2 필드에 오류를 추가
            self.add_error("password2", "비밀번호가 일치하지 않습니다")

    def save(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        password2 = self.cleaned_data['password2']
        profile_image = self.cleaned_data.get('profile_image')

        if profile_image is None:
            profile_image = os.path.join(settings.MEDIA_ROOT, 'users/profile/profile_default.png')

        user = User.objects.create_user(
            username=username,
            password=password,
            profile_image=profile_image,
        )
        return user

pastagram/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from .forms import LoginForm, SignupForm
from .models import User
import os


def login_view(request):
    if request.user.is_authenticated:
        return redirect("/posts/feeds/")

    if request.method == "POST":
        form = LoginForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                return redirect("/posts/feeds/")
            else:
                if not User.objects.filter(username=username).exists():
                    form.add_error("username", "아이디가 존재하지 않습니다.")
                else:
                    form.add_error("password", "비밀번호를 잘못 입력했습니다.")
    else:
        form = LoginForm()

    context = {"form": form}
    return render(request, "users/login.html", context)


def logout_view(request):
    logout(request)  
    return redirect("/users/login/")


def signup(request):
    if request.method == "POST":
        form = SignupForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)

            basicprofile_path = os.path.join(settings.MEDIA_ROOT, 'users/profile/basicProfile/basic.png')
            if os.path.isfile(basicprofile_path):
                os.remove(basicprofile_path)
            return redirect("/posts/feeds/")
        # POST 요청에서 form이 유효하지 않다면, 아래의 context = ... 부분으로 이동한다.

    # GET 요청 시, 빈 form을 생성한다.
    else:
        form = SignupForm()
    context = {"form": form}
    return render(request, "users/signup.html", context)

def profile(request, user_id):
    user = get_object_or_404(User, id=user_id)

    request.session.pop('selected_img_urls', None)
    
    context = {
        "user": user,
    }
    return render(request, "users/profile.html", context)

def followers(request, user_id):
    user = get_object_or_404(User, id=user_id)
    relationships = user.follower_relationships.all()
    context = {
        "user": user,
        "relationships": relationships,
    }
    return render(request, "users/followers.html", context)

def following(request, user_id):
    user = get_object_or_404(User, id=user_id)
    relationships = user.following_relationships.all()
    context = {
        "user": user,
        "relationships": relationships,
    }
    return render(request, "users/following.html", context)

def follow(request, user_id):
    # 로그인한 유저
    user = request.user
    # 팔로우하려는 유저
    target_user = get_object_or_404(User, id=user_id)

    # 팔로우하려는 유저가 이미 자신의 팔로잉 목록에 있는 경우
    if target_user in user.following.all():
        # 팔로잉 목록에서 제거
        user.following.remove(target_user)

    # 팔로우하려는 유저가 자신의 팔로잉 목록에 없는 경우
    else:
        # 팔로잉 목록에 추가
        user.following.add(target_user)

    # 팔로우 토글 후 이동할 URL이 전달되었다면 해당 주소로,
    # 전달되지 않았다면 로그인 한 유저의 프로필 페이지로 이동
    url_next = request.GET.get("next") or reverse("users:profile", args=[user.id])
    return HttpResponseRedirect(url_next)

pastagram/templates/users/followers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base-posts-profile.html' %}
{% block bottom_data %}
<div class="relationships">
  <h3>Followers</h3>
  {% for relationship in relationships %}
  <div class="relationship">
    <a href="{% url 'users:profile' user_id=relationship.from_user.id %}">
      {% if relationship.from_user.profile_image %}
        <img src="{{ relationship.from_user.profile_image.url }}">
      {% endif %}
      <div class="relationship-info">
        <span>{{ relationship.from_user.username }}</span>
        <span>{{ relationship.created|date:"y.m.d" }}</span>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}
</body>
</html>

pastagram/templates/users/following.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base-posts-profile.html' %}
{% block bottom_data %}
<div class="relationships">
  <h3>Following</h3>
  {% for relationship in relationships %}
  <div class="relationship">
    <a href="{% url 'users:profile' user_id=relationship.to_user.id %}">
      {% if relationship.to_user.profile_image %}
        <img src="{{ relationship.to_user.profile_image.url }}">
      {% endif %}
      <div class="relationship-info">
        <span>{{ relationship.to_user.username }}</span>
        <span>{{ relationship.created|date:"y.m.d" }}</span>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}
</body>
</html>

pastagram/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% extends 'base-users.html' %}

</head>
<body>
{% block content %}
    <div id="login">
        <form method="POST">
            <h1>Pystagram</h1>
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit" class="btn btn-login">로그인</button>
            <a href="/users/signup/">회원가입 페이지로 이동</a>

        </form>
    </div>
{% endblock %}

</body>
</html>

pastagram/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base-posts-profile.html' %}
{% block bottom_data %}
    <!-- 사용자가 작성한 Post 목록 -->
    <div class="post-grid-container" id="aa">
        {% for post in user.post_set.all %}
            {% if post.postimage_set.first and post.postimage_set.first.photo %}
                <div class="post-grid" id="bb">
                    <a href="{% url 'posts:post_detail' post_id=post.id %}">
                        <img src="{{ post.postimage_set.first.photo.url }}" alt="" id="posts_photo_id">
                    </a>
                </div>
            {% endif %}
        {% endfor %}
</div>
{% endblock %}
</body>
</html>

pastagram/templates/users/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        {% extends 'base-users.html' %}

</head>
<body>
{% block content %}
<div id="signup">
    <form method="POST" enctype="multipart/form-data">
        <h1>Pystagram</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-signup">가입</button>
        <a href="{% url 'users:login' %}">로그인 페이지로 이동</a>
    </form>
</div>
{% endblock %}

</body>
</html>