pastagram/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(prefix=settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pastagram/posts/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .views import feeds, comment_add, comment_delete, post_add, \
tags, post_detail, post_like, search_img, select_img


app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name="feeds"),
    path("comment_add/", comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>", comment_delete, name="comment_delete"),
    path("post_add/", post_add, name="post_add"),
    path("tags/<str:tag_name>", tags, name="tags"),
    path("<int:post_id>/", post_detail, name="post_detail"),
    path("<int:post_id>/like/", post_like, name="post_like"),
    path("search_img/", search_img, name="search_img"),
    path("select_img/", select_img, name="select_img"),

]

pastagram/users/urls.py
from django.urls import path
from .views import login_view, logout_view, signup, profile, followers, following, follow

app_name = "users"
urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup, name="signup"),
    path("<int:user_id>/profile/", profile, name="profile"),
    path("<int:user_id>/followers/", followers, name="followers"),
    path("<int:user_id>/following/", following, name="following"),
    path("<int:user_id>/follow/", follow, name="follow"),

]

pastagram/posts/models.py
from django.db import models
from django.core.files import File
from tempfile import NamedTemporaryFile
import requests

class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    content = models.TextField("내용", blank=True, null=True)
    created = models.DateTimeField("생성일시", auto_now_add=True)
    tags = models.ManyToManyField("posts.HashTag", verbose_name="해시태그 목록", blank=True)

    def __str__(self):
        return f"{self.user.username}의 Post(id: {self.id})"

class PostImage(models.Model):

    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE,
    )
    photo = models.ImageField("사진", upload_to="post")
    image_url = models.URLField(blank=True, null=True)


    def save_image_from_url(self, keyword, user):
        response = requests.get(self.image_url)
        if response.status_code == 200:
            img_temp = NamedTemporaryFile(delete=True)
            img_temp.write(response.content)
            img_temp.flush()
            self.photo.save(f"{user}_{keyword}_image.jpg", File(img_temp), save=True)


class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,   # 한 줄 건너뛰어서 괄호를 닫았으니 ,을 찍어야 한다.
    )
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE) # 바로 닫았으니 , 필요없음
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)

class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

pastagram/templates/base-posts-profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base-posts.html' %}
{% block content %}
<main class="profile-main">

    <div class="info_div">
        <!-- 프로필 이미지 영역 -->


        <!-- 사용자 정보 영역 -->
            <div class="profile_info_class">
             {% if user.profile_image %}
            <img src="{{ user.profile_image.url }}" class="profile-img">
            {% endif %}
                <div id="username_id">{{ user.username }} </div>
                </div>


   <div class="users_profile_info">
             <a href="{% url 'users:profile' user_id=user.id %}">
      Posts {{ user.post_set.count }}</a>
</div>

   <div class="users_profile_info">
          <a href="{% url 'users:followers' user_id=user.id %}">
     Followers {{ user.followers.count }}</a>
     </div>

     <div class="users_profile_info">
           <a href="{% url 'users:following' user_id=user.id %}">
     Following {{ user.following.count }}</a>
       </div>


            <p>{{ user.short_description }}</p>
    </div>

    {% block bottom_data %}{% endblock %}
</main>
{% endblock %}
</body>
</html>

pastagram/templates/base-posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  {% extends 'base.html' %}

  {% load static %}
  {% block head %}
    <link rel="stylesheet" href="{% static 'splide/splide.css' %}">
  {% endblock %}
</head>
<body>
  {% block base_content %}
    <main class="nav-posts-display">

      {% include 'nav.html' %}

      <article class="posts-base-container">
        {% block content %}{% endblock %}
      </article>
    </main>

    <script type="text/javascript" src="{% static 'splide/splide.js' %}"></script>
    <script type="text/javascript" src="{% static 'splide/splide_set.js' %}"></script>

  {% endblock %}
</body>
</html>


</head>
<body>

pastagram/templates/base-users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% extends 'base.html' %}

    {% block head %}
    {% endblock %}
</head>
<body>

{% block base_content %}
  {% block content %}{% endblock %}
{% endblock %}
</body>
</body>
</html>

pastagram/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <link rel="stylesheet" href="{% static 'css/baseStyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/usersStyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">

    <link rel="stylesheet" href="{% static 'css/nav.css' %}">



  {% block head %}{% endblock %}
</head>
<body>

  {% block base_content %}{% endblock %}
  <script type="text/javascript" src="{% static 'js/style.js' %}"></script>

</body>
</html>


pastagram/templates/nav.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
</head>
<body>
 -->

<nav class="posts-nav">
    <h1>
        <a href="{% url 'posts:feeds' %}" id="main-name">Pastagram</a>
    </h1>
    <ul id="ul-list-id">
        <li id="li-list-id">
                <a class="aside-list" href="{% url 'posts:post_add' %}">
               <img src="{% static 'image/add_post.png' %}" class="aside-list-img">
                    게시물 작성</a>
        </li>

        <li id="li-list-id">
            <a class="aside-list" href="{% url 'users:profile' user_id=user.id %}">
                {% if user.profile_image %}
                <img src="{{ user.profile_image.url }}" class="profile-img">
                {% else %}
                <img src="{% static 'image/profile_default.png' %}" class="profile-img">
                {% endif %}
                프로필</a>
        </li>
        
        <li>
            <a class="aside-list" href="{% url 'users:logout' %}">
            <img src="{% static 'image/logout.png' %}" class="aside-list-img">
                로그아웃</a>
        </li>
    </ul>
</nav>

<!-- </body>
</html> -->

pastagram/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    check~~
</body>
</html>